services:
  app:
    build: .
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      jaeger:
        condition: service_started
    command: [ "python", "-Om", "main" ]

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317:4317"